line-length = 120
target-version = "py312"
exclude = ["*/migrations/*"]

[lint]
select = ["E", "F", "I", "B", "UP"]
ignore = [
    "B904",   # raise ... from err
    "UP007",  # X | Y вместо Optional[X]
]

[lint.per-file-ignores]
"apps/core/utils.py" = ["E402"]

[format]
quote-style = "single"
